import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}> 
        <br />
        <h2><ConnectButton accountStatus="address" /></h2>
        <h1 className={styles.title}>
          Welcome to Wallet Connection 
        </h1>
      </main>
      <footer className={styles.footer}>
          Made with ❤️ by 0xDiv
      </footer>
    </div>
  );
};

export default Home;
